# Generated by Django 5.0.4 on 2024-04-19 13:04

import python_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='constructionyear',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='energylabel',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='imageurl',
            field=models.URLField(default=python_django.models.default_image_url),
        ),
        migrations.AddField(
            model_name='home',
            name='municipality',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='squaremeters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
