# Generated by Django 5.0.4 on 2024-04-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0002_home_constructionyear_home_energylabel_home_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home',
            table='homes',
        ),
    ]
