# Generated by Django 5.0.6 on 2024-06-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_django', '0003_alter_home_table_favorite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='home',
            table='homes',
        ),
    ]
